name: Test and Lint

on: [push]

env:
  PYTHON_VERSION: 3.11.4

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Pylint
        run: |
          pylint $(git ls-files '*.py')

  Test:
    # The latest ubunut runner image (ubuntu-22.04) does not work with the
    # python:3.11.4-bullseye container image. So we use ubuntu-20.04 instead.
    runs-on: ubuntu-20.04
    # The container image should match the backend Dockerfile.
    container: python:3.11.4-bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m